# Start from the Ubuntu base image
FROM ubuntu:latest

# Install curl, unzip, git, procps (provides ps for Node.js debugger)
# Also clean up apt cache to keep image size down
RUN apt-get update && apt-get -y install curl apt-utils unzip git wget procps htop
RUN rm -rf /var/lib/apt/lists/*

# Install Node.js v18
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs

# Set the default shell to bash rather than sh
ENV SHELL /bin/zsh
# Uses "git", "ssh-agent" and "history-substring-search" bundled plugins
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t cloud \
    -p git -p 'history-substring-search' \
    -a 'bindkey "\$terminfo[kcuu1]" history-substring-search-up' \
    -a 'bindkey "\$terminfo[kcud1]" history-substring-search-down'