name: Build App using PNPM

on:
  push:
    branches:
      - main
      - maintenance/workflows
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Install app dependencies
        run: |
          pnpm install

      - name: Build app
        run: |
          pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: ./dist
