name: Build App using PNPM

on:
  push:
    branches:
      - main
      - develop
      - maintenance/workflows
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install GitVersion
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          configFilePath: './gitversion.yml'

      - name: Set Package Version
        id: set_package_version
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          git config --global user.email "build-server@github.com"
          git config --global user.name "build-server"
          echo "Setting version to: ${{ env.GitVersion_MajorMinorPatch }}"
          npm version ${{ env.GitVersion_MajorMinorPatch }}
          
      - name: Install PNPM
        run: |
          npm install -g pnpm

      - name: Install app dependencies
        run: |
          pnpm install

      - name: Build app
        run: |
          pnpm build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: built-app
          path: ./dist
